name: Build Dev
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Lavalink Dev Branch Version'     
        required: true
        default: 'null'
      tag:
        description: 'Release tag name'     
        required: true
        default: 'null'
      release_body:
        description: 'Release body notes'     
        required: true
        default: 'null'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          IMG=lavalink
          OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "IMG=${IMG}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${OWNER}/${IMG}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Java v17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download & Repack Lavalink.jar
        run: |
          wget "https://ci.fredboat.com/repository/download/Lavalink_Build/${{ env.VERSION }}:id/Lavalink.jar?guest=1" -O Lavalink.jar;
          wget https://github.com/aikaterna/lavaplayer-natives/raw/master/linux-aarch64/libconnector.so
          mkdir -p Lavalink-patch/lavaplayer-natives-patch; pushd Lavalink-patch
          unzip ../Lavalink.jar
          pushd lavaplayer-natives-patch
          unzip ../BOOT-INF/lib/lavaplayer-natives*.jar
          mkdir -p natives/linux-aarch64/
          cp ../../libconnector.so natives/linux-aarch64
          jar -cvfm ../BOOT-INF/lib/lavaplayer-natives*.jar META-INF/MANIFEST.MF .
          popd; rm -rf lavaplayer-natives-patch
          jar -cvf0m ../LavalinkDevARM64.jar META-INF/MANIFEST.MF .
          popd; rm -rf Lavalink-patch

      - name: Release LavalinkDevARM64.jar
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "(dev build) ${{ github.event.inputs.tag }}"
          body: ${{ github.event.inputs.release_body }}
          files: LavalinkDevARM64.jar
